sonar.projectKey=NicolasOmar_meds-warning
sonar.organization=nicolasomar

# relative paths to source directories. More details and properties are described
# in https://docs.sonarcloud.io/advanced-setup/analysis-scope/
sonar.sources=actions/,app/,components/,prisma/,shared/
sonar.tests=actions/,app/,components/,prisma/,shared/
sonar.inclusions=actions/**/*.ts,app/**/*.tsx,components/**/*.ts,prisma/**/*.ts,shared/**/*.ts
sonar.exclusions=actions/**/*.test.ts,app/**/*.test.tsx,app/concept/**/*,components/**/*.test.ts,prisma/**/*.test.ts,shared/**/*.test.ts
sonar.test.inclusions=actions/**/*.test.ts,app/**/*.test.tsx,components/**/*.test.ts,prisma/**/*.test.ts,shared/**/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info