import type { Metadata } from 'next'
import Link from 'next/link'
// COMPONENTS
import { Item, ItemContent } from '@base-components/item'
import { ButtonGroup } from '@base-components/button-group'
import { Button } from '@base-components/button'
// CONSTANTS
import { ROUTES_OBJS } from '@ts/constants'
// STYLES
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-6`}>
        <header className="m-4 col-span-full justify-self-center">
          <ButtonGroup orientation={'vertical'}>
            {ROUTES_OBJS.map(({ name, path }, routeId) => {
              return (
                <Button key={routeId}>
                  <Link href={path} className="text-2xl font-medium text-white-600 hover:underline">
                    {name}
                  </Link>
                </Button>
              )
            })}
          </ButtonGroup>
        </header>
        <section className="col-start-2 col-span-4">
          <Item>
            <ItemContent>{children}</ItemContent>
          </Item>
        </section>
      </body>
    </html>
  )
}
